/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAiVisibilityRouteImport } from './routes/_site/ai-visibility'
import { Route as SiteCalatoriaRouteImport } from './routes/_site/calatoria'
import { Route as SiteCarteRouteImport } from './routes/_site/carte'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteDespreRouteImport } from './routes/_site/despre'
import { Route as SitePresaRouteImport } from './routes/_site/presa'
import { Route as SiteAdminAbonatiRouteImport } from './routes/_site/admin/abonati'
import { Route as SiteAdminCranditRouteImport } from './routes/_site/admin/crandit'
import { Route as SiteAdminMesajeRouteImport } from './routes/_site/admin/mesaje'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog/index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog/$slug'
import { Route as SiteLabIndexRouteImport } from './routes/_site/lab/index'
import { Route as SiteLabSlugRouteImport } from './routes/_site/lab/$slug'
import { Route as SiteProiecteIndexRouteImport } from './routes/_site/proiecte/index'
import { Route as SiteProiecteSlugRouteImport } from './routes/_site/proiecte/$slug'
import { Route as SiteProiecteGeoAiVisibilityRouteImport } from './routes/_site/proiecte/geo-ai-visibility'
import { Route as SiteLabParentSlugRouteImport } from './routes/_site/lab/$parent.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAiVisibilityRoute = SiteAiVisibilityRouteImport.update({
  id: '/ai-visibility',
  path: '/ai-visibility',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCalatoriaRoute = SiteCalatoriaRouteImport.update({
  id: '/calatoria',
  path: '/calatoria',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCarteRoute = SiteCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDespreRoute = SiteDespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => SiteRoute,
} as any)
const SitePresaRoute = SitePresaRouteImport.update({
  id: '/presa',
  path: '/presa',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminAbonatiRoute = SiteAdminAbonatiRouteImport.update({
  id: '/admin/abonati',
  path: '/admin/abonati',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminCranditRoute = SiteAdminCranditRouteImport.update({
  id: '/admin/crandit',
  path: '/admin/crandit',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminMesajeRoute = SiteAdminMesajeRouteImport.update({
  id: '/admin/mesaje',
  path: '/admin/mesaje',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLabIndexRoute = SiteLabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLabSlugRoute = SiteLabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProiecteIndexRoute = SiteProiecteIndexRouteImport.update({
  id: '/proiecte/',
  path: '/proiecte/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProiecteSlugRoute = SiteProiecteSlugRouteImport.update({
  id: '/proiecte/$slug',
  path: '/proiecte/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProiecteGeoAiVisibilityRoute =
  SiteProiecteGeoAiVisibilityRouteImport.update({
    id: '/proiecte/geo-ai-visibility',
    path: '/proiecte/geo-ai-visibility',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteLabParentSlugRoute = SiteLabParentSlugRouteImport.update({
  id: '/lab/$parent/$slug',
  path: '/lab/$parent/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/ai-visibility': typeof SiteAiVisibilityRoute
  '/calatoria': typeof SiteCalatoriaRoute
  '/carte': typeof SiteCarteRoute
  '/contact': typeof SiteContactRoute
  '/despre': typeof SiteDespreRoute
  '/presa': typeof SitePresaRoute
  '/admin/abonati': typeof SiteAdminAbonatiRoute
  '/admin/crandit': typeof SiteAdminCranditRoute
  '/admin/mesaje': typeof SiteAdminMesajeRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/lab/$slug': typeof SiteLabSlugRoute
  '/proiecte/$slug': typeof SiteProiecteSlugRoute
  '/proiecte/geo-ai-visibility': typeof SiteProiecteGeoAiVisibilityRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/lab/': typeof SiteLabIndexRoute
  '/proiecte/': typeof SiteProiecteIndexRoute
  '/lab/$parent/$slug': typeof SiteLabParentSlugRoute
}
export interface FileRoutesByTo {
  '/ai-visibility': typeof SiteAiVisibilityRoute
  '/calatoria': typeof SiteCalatoriaRoute
  '/carte': typeof SiteCarteRoute
  '/contact': typeof SiteContactRoute
  '/despre': typeof SiteDespreRoute
  '/presa': typeof SitePresaRoute
  '/': typeof SiteIndexRoute
  '/admin/abonati': typeof SiteAdminAbonatiRoute
  '/admin/crandit': typeof SiteAdminCranditRoute
  '/admin/mesaje': typeof SiteAdminMesajeRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/lab/$slug': typeof SiteLabSlugRoute
  '/proiecte/$slug': typeof SiteProiecteSlugRoute
  '/proiecte/geo-ai-visibility': typeof SiteProiecteGeoAiVisibilityRoute
  '/blog': typeof SiteBlogIndexRoute
  '/lab': typeof SiteLabIndexRoute
  '/proiecte': typeof SiteProiecteIndexRoute
  '/lab/$parent/$slug': typeof SiteLabParentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/ai-visibility': typeof SiteAiVisibilityRoute
  '/_site/calatoria': typeof SiteCalatoriaRoute
  '/_site/carte': typeof SiteCarteRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/despre': typeof SiteDespreRoute
  '/_site/presa': typeof SitePresaRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/admin/abonati': typeof SiteAdminAbonatiRoute
  '/_site/admin/crandit': typeof SiteAdminCranditRoute
  '/_site/admin/mesaje': typeof SiteAdminMesajeRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/lab/$slug': typeof SiteLabSlugRoute
  '/_site/proiecte/$slug': typeof SiteProiecteSlugRoute
  '/_site/proiecte/geo-ai-visibility': typeof SiteProiecteGeoAiVisibilityRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/lab/': typeof SiteLabIndexRoute
  '/_site/proiecte/': typeof SiteProiecteIndexRoute
  '/_site/lab/$parent/$slug': typeof SiteLabParentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-visibility'
    | '/calatoria'
    | '/carte'
    | '/contact'
    | '/despre'
    | '/presa'
    | '/admin/abonati'
    | '/admin/crandit'
    | '/admin/mesaje'
    | '/blog/$slug'
    | '/lab/$slug'
    | '/proiecte/$slug'
    | '/proiecte/geo-ai-visibility'
    | '/blog/'
    | '/lab/'
    | '/proiecte/'
    | '/lab/$parent/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-visibility'
    | '/calatoria'
    | '/carte'
    | '/contact'
    | '/despre'
    | '/presa'
    | '/'
    | '/admin/abonati'
    | '/admin/crandit'
    | '/admin/mesaje'
    | '/blog/$slug'
    | '/lab/$slug'
    | '/proiecte/$slug'
    | '/proiecte/geo-ai-visibility'
    | '/blog'
    | '/lab'
    | '/proiecte'
    | '/lab/$parent/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/_site/ai-visibility'
    | '/_site/calatoria'
    | '/_site/carte'
    | '/_site/contact'
    | '/_site/despre'
    | '/_site/presa'
    | '/_site/'
    | '/_site/admin/abonati'
    | '/_site/admin/crandit'
    | '/_site/admin/mesaje'
    | '/_site/blog/$slug'
    | '/_site/lab/$slug'
    | '/_site/proiecte/$slug'
    | '/_site/proiecte/geo-ai-visibility'
    | '/_site/blog/'
    | '/_site/lab/'
    | '/_site/proiecte/'
    | '/_site/lab/$parent/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ai-visibility': {
      id: '/_site/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/ai-visibility'
      preLoaderRoute: typeof SiteAiVisibilityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/calatoria': {
      id: '/_site/calatoria'
      path: '/calatoria'
      fullPath: '/calatoria'
      preLoaderRoute: typeof SiteCalatoriaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/carte': {
      id: '/_site/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof SiteCarteRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/despre': {
      id: '/_site/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof SiteDespreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/presa': {
      id: '/_site/presa'
      path: '/presa'
      fullPath: '/presa'
      preLoaderRoute: typeof SitePresaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin/abonati': {
      id: '/_site/admin/abonati'
      path: '/admin/abonati'
      fullPath: '/admin/abonati'
      preLoaderRoute: typeof SiteAdminAbonatiRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin/crandit': {
      id: '/_site/admin/crandit'
      path: '/admin/crandit'
      fullPath: '/admin/crandit'
      preLoaderRoute: typeof SiteAdminCranditRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin/mesaje': {
      id: '/_site/admin/mesaje'
      path: '/admin/mesaje'
      fullPath: '/admin/mesaje'
      preLoaderRoute: typeof SiteAdminMesajeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lab/': {
      id: '/_site/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof SiteLabIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lab/$slug': {
      id: '/_site/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof SiteLabSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/proiecte/': {
      id: '/_site/proiecte/'
      path: '/proiecte'
      fullPath: '/proiecte/'
      preLoaderRoute: typeof SiteProiecteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/proiecte/$slug': {
      id: '/_site/proiecte/$slug'
      path: '/proiecte/$slug'
      fullPath: '/proiecte/$slug'
      preLoaderRoute: typeof SiteProiecteSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/proiecte/geo-ai-visibility': {
      id: '/_site/proiecte/geo-ai-visibility'
      path: '/proiecte/geo-ai-visibility'
      fullPath: '/proiecte/geo-ai-visibility'
      preLoaderRoute: typeof SiteProiecteGeoAiVisibilityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lab/$parent/$slug': {
      id: '/_site/lab/$parent/$slug'
      path: '/lab/$parent/$slug'
      fullPath: '/lab/$parent/$slug'
      preLoaderRoute: typeof SiteLabParentSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAiVisibilityRoute: typeof SiteAiVisibilityRoute
  SiteCalatoriaRoute: typeof SiteCalatoriaRoute
  SiteCarteRoute: typeof SiteCarteRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDespreRoute: typeof SiteDespreRoute
  SitePresaRoute: typeof SitePresaRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAdminAbonatiRoute: typeof SiteAdminAbonatiRoute
  SiteAdminCranditRoute: typeof SiteAdminCranditRoute
  SiteAdminMesajeRoute: typeof SiteAdminMesajeRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteLabSlugRoute: typeof SiteLabSlugRoute
  SiteProiecteSlugRoute: typeof SiteProiecteSlugRoute
  SiteProiecteGeoAiVisibilityRoute: typeof SiteProiecteGeoAiVisibilityRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteLabIndexRoute: typeof SiteLabIndexRoute
  SiteProiecteIndexRoute: typeof SiteProiecteIndexRoute
  SiteLabParentSlugRoute: typeof SiteLabParentSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAiVisibilityRoute: SiteAiVisibilityRoute,
  SiteCalatoriaRoute: SiteCalatoriaRoute,
  SiteCarteRoute: SiteCarteRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDespreRoute: SiteDespreRoute,
  SitePresaRoute: SitePresaRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteAdminAbonatiRoute: SiteAdminAbonatiRoute,
  SiteAdminCranditRoute: SiteAdminCranditRoute,
  SiteAdminMesajeRoute: SiteAdminMesajeRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteLabSlugRoute: SiteLabSlugRoute,
  SiteProiecteSlugRoute: SiteProiecteSlugRoute,
  SiteProiecteGeoAiVisibilityRoute: SiteProiecteGeoAiVisibilityRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteLabIndexRoute: SiteLabIndexRoute,
  SiteProiecteIndexRoute: SiteProiecteIndexRoute,
  SiteLabParentSlugRoute: SiteLabParentSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
